### ISSUE TITLE
Discordでのtimesについて

### ISSUE THREAD

**Issue by shoumoji** [HUITGroup/meeting#11]
## WHAT
Discordでのtimesをどうするか考えたい。

## WHY
twitterには出したくないが、技術的な話題をtimesに度々書くので、Discordではどうするか決めておきたい。  

## 具体例(提案)
- timesチャンネルは作成時デフォルトでミュート状態で、見たい人のチャンネルだけ各自でミュート解除してみてもらう。  
- timesは部員以外(ゲスト参加者)からは見えない。

**Comment by Tatmius** [comment]
個人的にはtimesはサークル内での会話が減るから少し反対ではあるものの、自由に発信できる場も欲しくはあるから、サークル内mastodon的なのがあるといいなぁと思いました。
チャット形式ではなくて、フィード形式のものがあるといいかなぁと。
もちろんツールが増えるとそれはそれでめんどくさいのはあると思うので、要検討ですが......

**Comment by noriHanda** [comment]
結構これが参考になると思います＆いいなと思いました。
<img width="824" alt="スクリーンショット 2020-11-29 12 49 57" src="https://user-images.githubusercontent.com/18581236/100532872-642f0c00-3241-11eb-8971-38a6acf6823d.png">

**Comment by shoumoji** [comment]
運営会議でmastdon作るのは良いかなとは思う一方
- 定着するか (放置されないか)
- みんな見てくれるのか
- twitterでよくね

等まだ考えなきゃいけないことはある感じ。

**Comment by TetsuFe** [comment]
「timesでどんな話がされることを想定しているか」各自書き出してみるといいんじゃ無いかと思った。

@noriHanda くんが引用してくれてる俺の投稿の意図としては、

- timesでどんな話がされることを想定しているか: 技術的な話、たわいのない雑談、質問・疑問・困っていることなど
- そういう話を気軽にできるようにしたい

という感じ。

@shoumoji くんとしては、
timesでどんな話がされることを想定しているか:  twitterには出したくないが、技術的な話題
ということでいいのかな？

だとすると、結構俺の意図とは違うことになると思う

多分、俺の投稿に同意？してくれてる半田くんも、俺と同じような話がされることを想定してるんじゃないかと思う

「timesでどんな話がされることを想定しているか」が各自で違ってくると、ゴールももちろん違ってくることになるから、ツールについて話し合ってみる前に、一度これを整理してみてはどうかな。

**Comment by shoumoji** [comment]
> @shoumoji くんとしては、
> timesでどんな話がされることを想定しているか: twitterには出したくないが、技術的な話題
> ということでいいのかな？

そんな感じです。技術的な話題を中心に考えてました。

技術に限らない場合、自分の場合はTwitterに普通にあげてしまうのであまりtimesを使うという発想がなかったです。

**Comment by Tatmius** [comment]
## 想定してるtimesでの話
「timesでどんな話がされることを想定しているか」のすり合わせは確かに大事ですね。

自分はどちらかというと、
「技術的な話を投稿しやすい空間は、たわいもない投稿も出来るぐらいの場所の方が良い」
と思っています。(理想としてはQiitadonぐらい)
「技術的な話か微妙やし投稿していいかわからん」みたいな気持ちが生じるとそれだけで投稿がめんどくさくなったり、投稿するネタがなくなったりするのではないかなと思ったからです。

極端なことを言えば、8割の非技術的な話に引っ張られて2割の技術的な話が出てくるようになったらいいかなと思ってます。

## 投稿数と活気
個人的にもう一つ大事やと思ってるのが、「投稿数」です。
オンラインの活動がメインになり、よりサークル活動の「活発さ」が投稿数によって目視できるようになりました。メンバーの顔も見えづらくなり、今までよりも仲良くなりづらいと思っています。
そんな中で技術的な話以外もガンガン投稿出来て、滞在時間が増えれば帰属意識も生まれるのではないかと思っています。

例えば、twitterで多くつぶやく人にはtwitter連携してもらってtwitterの内容をHUITに流すみたいなことも出来ればよいのかなとかも思っています。

このissueの本来のテーマに戻すと、
- 全員がtimesを作る
- 非技術的な話も積極的に投稿するようにする

みたいなところが具体的な案になります。(多分他にも何か手を打つべきではある)
自分がmastodonを出したのは、技術的な話も非技術的な話もガンガン出来る(しやすい)場所として良さそうやなと思ったからです。

**Comment by shoumoji** [comment]
## 話題について

活気を考えると、ガンガンtimesに投稿した方が良いのは賛成です。非技術の話題をどんどんすると自然と活気があるサークルになりそうですし。

## マストドンについて

自分は極力discord+GitHubにツールをまとめたいので、マストドン化はあまり賛成できないです。  
既にあるDiscord上ですむような形にできた方が、見てくれる人は多いはずなので。

## times全員作成について

あまり弊害がないので行っても良いと思いますが、Discordのtimesチャンネルが並びまくって凄いことになりそうです。

一番上に、全員のtimesをtimeline形式でまとめたtimelineチャンネルとか作ると良さそうな気がします。

**Comment by TetsuFe** [comment]
@Tatmius @shoumoji 
意思決定をIssueを作った人がリードするのか、部長がリードするのかなんとなく共通認識があった方がより議論がスムーズにいくかも、と思った。
全て部長がリードするのはきついから、基本的にはIssueを作った人(あるいはassigner)がリードする方がいいと思うけど。

(意思決定をリードするとは、例えば「これで決定でいいですか？」とか「これとこれどっちがいいですか？」みたいな発言をすること)

**Comment by shoumoji** [comment]
> 全て部長がリードするのはきついから、基本的にはIssueを作った人(あるいはassigner)がリードする方がいいと思うけど。

そうですね。とりあえず現状意見がまとまってそうな
- 賛成者が多そうな積極的なtimes投稿. timesの作成の推奨を進める(少なくとも運営は全員ほしい)
は行う方向で良いでしょうか。良ければ、部員がtimesを自由に作れるよう、Discordの権限を変更しようかと思います。

マストドンと全員times強制は、次の例会か運営会議でもう少し議論したいので、いったん保留でどうでしょう。

**Comment by Tatmius** [comment]
返信遅くなって申し訳ないです。

>積極的なtimes投稿
>timesの作成の推奨を進める

まずMVPとしてこの方向で行くのは賛成です。
個人的には例会まで待たずにすぐに運営メンバー内でコンセンサス取り次第実施できればと思います。

>一番上に、全員のtimesをtimeline形式でまとめたtimelineチャンネルとか作ると良さそうな気がします。

これ、めちゃくちゃ良いと思っていて、自分はそのtimelineチャンネルに例えばtwitterを多く使う人ならtwitter連携でそのtimelineにツイートが流せるといいかなと思ってました。


これはまた今後の議題ですけど、timelineチャンネルのメリットである『時系列やけど、会話ではなく(とはいえ会話も発生しうる)、気軽に投稿出来る場所があればコミュニティが作れるのでは』というのがmastodonを提案した時の気持ちでした。もちろんその実現方法は複数あるはずです。
