### ISSUE TITLE
HUITの読み方

### ISSUE THREAD

**Issue by takapiro99** [HUITGroup/meeting#16]
## 概要

HUITの読み方、なにか公式なものがあったほうが
いいかも？

## 目的

　

サークルのことを自称するときに困るから

## TODO

- [ ] いくつか提案してもらう
- [ ] みんなで意見を言う
- [ ] 投票などで決める

## 留意事項

- 
-

## 検討事項

- 
-

**Comment by takapiro99** [comment]
ヒュイット

**Comment by takapiro99** [comment]
フイット

**Comment by takapiro99** [comment]
エイチユーアイティー

**Comment by noriHanda** [comment]
ウイッ

**Comment by ShijiMi-Soup** [comment]
フランス語読みを言いやすくしを「ユイット」推し

**Comment by shoumoji** [comment]
あえて統一しない、に一票  
各々サークル名であることは分かると思うので、自分が親しみやすい音で呼ぶのが良い気がします

**Comment by manattan** [comment]
ウィット
（フランス語っぽいけど違う）

**Comment by shoumoji** [comment]
外部(企業など)向けには エイチユーアイティー , サークル内ではご自由にどうぞ
