### ISSUE TITLE
例会やgithubで発言しにくい人への配慮をしたい

### ISSUE THREAD

**Issue by shoumoji** [HUITGroup/meeting#17]
## 目的
例会のシーンとした中で発言するのは(運営の人でも)心理的障壁が高いので、良い発言手段を考えたい。  
また、GitHubも運営以外がほとんど使っていない。あまり運営に関わっていない人が意見を言うのが難しくなっているのでは。

## 参考
発言は喋る以外にも、チャットなどでも良い。  
人によってはDiscordのチャットでも難しいと思うので、気軽に匿名で意見を伝えられる場所が欲しい。  

## 留意事項
- 心理的障壁が下がれば問題はない
- 並行して長期的な例会自体の改善も考えるべき
    - ただし最近は特に決めることが多いので、今すぐ使える手段が必要(今回のissueはこっち)

## 検討事項
- slidoの導入など

**Comment by takapiro99** [comment]
どこかの(ディスコの)全体チャンネルにここのコメント流すようにしたらとりあえず見てはくれそう

**Comment by manattan** [comment]
それです！

**Comment by shoumoji** [comment]
ディスコにGitHubチャンネル作ってそこに流しますか

**Comment by shoumoji** [comment]
GitHubチャンネル作りました、あとは発言しやすい仕組みづくりの方ですね
