### ISSUE TITLE
新春ハッカソンやりたくないですか?

### ISSUE THREAD

**Issue by manattan** [HUITGroup/meeting#19]
## 概要
- みんなとハッカソンしたい（）

## 検討事項

- [ ] 短期型か長期型かの選択
    - 短期型なら, 1/15キックオフ1/17発表?この場合エントリーはいつまで??
    - 長期型なら1/8キックオフ1/17発表?(これは長期なのか)
- [ ] エントリー方法
    - 個人エントリー& キックオフにチーム発表?
    - チームエントリー?

**Comment by takapiro99** [comment]
やらなかった
