### ISSUE TITLE
今後のHUITの方向性

### ISSUE THREAD

**Issue by shoumoji** [HUITGroup/meeting#20]
## 概要

今の方針で1年間やってきたが、実際のところオンラインに活動の場を移したことによって、人が集まりにくくなっていたりなどの問題が出てきています。

そこで、HUITの今後の方向性をすり合わせておきたいです。

2/5までにHUITにどうあってほしいかなどをお願いします。

## TODO

- [ ]
- [ ]
- [ ]

## 留意事項

-
-

## 検討事項

-
-

**Comment by manattan** [comment]
具体的な人数はそこまで重要ではない気がするけど, 少なくとも自分自身が成長できる予感がするコミュニティにできればいいのではないかと思います

- 初心者も積極的に参加できる勉強会の開催
- LT会をいっぱいやる　（みるぐらいなら発表しようぜ的な雰囲気が見受けられたけど, そんなことしないでもっと気軽に参加できるような状態がいいのかなと思う）
- ハッカソンは必須ですね（え）

**Comment by shoumoji** [comment]
- やりたいことはある、だけどまず何から手をつけるべきか分からない、という人を導けること
- 技術者/エンジニアとして将来を考えている人、何か特定の技術が得意/好きな人が居心地の良いサークルであること
というのが、自分の理想とするサークル像です。

後者は熟練者だけではなくて、初心者でも話しやすい、疑問を公開しやすい環境を作っていきたいなと思います。

勿論勉強会も良いですが、今はそもそも普通に仲良くなる機会自体が足りてない気がします。  
そういった意味では、among usなどで普段活動に来ない方が来ているのはとても良い傾向だと思います。(それだけで良い、というわけではないのですが)

また当分の間オンラインは続くと思うので、オンライン前提のサークル活動を作るべきだと思います。

活動自体zoomとかでカメラ有り推奨にしても良いのかもしれません(実際seccampの懇親会とかはそんな感じで話しやすく感じたので)

**Comment by manattan** [comment]
> カメラ有り推奨にしても良いのかもしれません

それな, 相手の顔わからないの, 普通に怖い

新歓は顔出しもしたいし, zoomとか良いかもね.
配信 + 専用discordサーバーでもいいかも

**Comment by shoumoji** [comment]
これちょっと話題が抽象的すぎて着地点がないので一旦閉じます

個別の問題に関しては個別のissuesで話し合いましょう
