### ISSUE TITLE
OBとの関わり方

### ISSUE THREAD

**Issue by TetsuFe** [HUITGroup/meeting#21]
## 概要
現役部員とOBとがいい感じに関わっていくにはどうしたらいいか考える

## 目的
普段の活動からOBが多いので、現役が参加しにくく感じているのではないか？
OBは現役とどう関わっていくべきか？
などの疑問の解消。お互い安心して活動に参加できるようにしたい

## TODO
- [ ] 現役からOBに求めるもの・不安など思うことをヒアリング
- [ ] OBの不安をヒアリング
- [ ] 何かイベントなどの提案があれば聞きたい
- など

## 参考
2/12のLTで @TetsuFe がLTでこの話題について話します。

## 留意事項
- @Tatmius くんがアクティブになったら、 @TetsuFe の方から声をかけます。それまでお待ちください
-

## 検討事項

-
-

**Comment by shoumoji** [comment]
## OB側からの不安として既に耳に入っているもの
- 学生団体に院生/社会人などが大量にいると本来メインであるはずの学生の活動を圧迫しないか
  - 特に初心者の発言を抑制してしまっていないか
- 活動の主体に社会人が複数人いるのは学生団体としてどうなのか
- 今後辞めるタイミングがなくなるのではないか


## 現状考えられる方向性 (他にあれば追記お願いします)
- 現状維持
  - このまま学生と社会人が混ざり合うサークルとしての形を取る
- 学生部/社会部に分ける
  - 通常活動は学生のみで、イベント系(LTなど)は社会人の人にも参加を仰ぐ、など緩やかに結ぶ
- 卒業してもらう
  - 以降も繋がりたい人は、あくまで個人的なものとして行う

**Comment by TetsuFe** [comment]
とりあえず @Tatmius くんは忙しそうなので他のメンバーで話しすすめることにしようかな

**Comment by TetsuFe** [comment]
正直なところ、優先度できには新歓終わったあたりで余裕出た時に話し合うのでもいいかなーと思ってる

**Comment by TetsuFe** [comment]
次回の例会で話し合うこと

- OBの定義
- 現役とOBの連絡手段、合同活動の方法
- 「社会人（学生でない人）の現役部員」はありか？
- 卒業のタイミング

**Comment by TetsuFe** [comment]
## 現状の案？
これまで自分が聞いた感じ以下のようになりそう？

- OBの定義
  - 大学、大学院生の間にHUITに入り、その後大学・大学院を卒業して社会人になった人
  - HUITの現役部員としての活動をやめて早めにOBになりたいと申し出た人
- 現役とOBの連絡手段、合同活動の方法
  - 連絡手段：discord等でDM
  - 合同活動の方法：上記のようにdiscord等で連絡をとり、zoom等で活動
- 「社会人（学生でない人）の現役部員」はありか？
  - 今後はなし？
  - 直にHUITのOBになることはできない
- 卒業のタイミング
  - 大学・大学院を卒業して社会人になったとき

**Comment by TetsuFe** [comment]
> ## OB側からの不安として既に耳に入っているもの
> * 学生団体に院生/社会人などが大量にいると本来メインであるはずの学生の活動を圧迫しないか
>   
>   * 特に初心者の発言を抑制してしまっていないか
> * 活動の主体に社会人が複数人いるのは学生団体としてどうなのか
> * 今後辞めるタイミングがなくなるのではないか
> 
> ## 現状考えられる方向性 (他にあれば追記お願いします)
> * 現状維持
>   
>   * このまま学生と社会人が混ざり合うサークルとしての形を取る
> * 学生部/社会部に分ける
>   
>   * 通常活動は学生のみで、イベント系(LTなど)は社会人の人にも参加を仰ぐ、など緩やかに結ぶ
> * 卒業してもらう
>   
>   * 以降も繋がりたい人は、あくまで個人的なものとして行う

この不安を持っている人はdiscordから抜けるようと決めていたと認識しています
つまり不安を解消するためになにかアクションを取る必要はなくなりました

**Comment by TetsuFe** [comment]
## OBの活動について
一旦連絡手段の確保ということでOB用のdiscordを作成しました。OB用のdiscordには現役部員も所属が可能ということにしようと思っています（一部週１以上でOBと話している現役部員もいますし、現役部員がOBに萎縮することはあっても逆はないと考えられるため）。

**Comment by shoumoji** [comment]
3月末までで結論を出す

**Comment by shoumoji** [comment]
まだOB自体ほとんどいないこともあり、来年度はサークルとして追い出すことはしない方針にしました。
