### ISSUE TITLE
通常活動を増やしたい

### ISSUE THREAD

**Issue by manattan** [HUITGroup/meeting#24]
## 概要
- 現状は, 金曜日の活動 + 不定期イベントになっている

## 目的
- 火曜日にも通常活動を行なって盛り上がって行きたくね？

## TODO

- [ ]
- [ ]
- [ ]

## 留意事項

-
-

## 検討事項

-
-

**Comment by shoumoji** [comment]
賛成です。

元々火曜の活動が消えたのは、参加人数が全く確保できなかった点が大きいです。

今は当時と状況がだいぶ違っていて、普通に人も集まりそうなので復活させても問題ないと思います。

**Comment by shoumoji** [comment]
不定期にもくもくする人がいることや、ハッカソンや勉強会等イベントが増えたため、通常活動を増やすことはしない方針になりました。
