### ISSUE TITLE
新春ハッカソンやりたくね?

### ISSUE THREAD

**Issue by manattan** [HUITGroup/meeting#26]
- やりたいので、皆さんで検討してからagendaのissueにしたいですね
- @manattan @takapiro99 @tanakarn98 @gojiteji ←引退してるけどやる？？？？（）

**Comment by shoumoji** [comment]
ハッカソンconnpass: https://huit.connpass.com/event/205019/
ハッカソン参加者向けdoc: https://hackmd.io/Ay5HIcSUSoS44uDTbeoEZQ
