### ISSUE TITLE
HUITの口座を作りたいのと、今後のサークルの公認化について

### ISSUE THREAD

**Issue by manattan** [HUITGroup/meeting#30]
- 公式サークルにしないと作れないわけではない（らしい？）ので、作りたいね

**Comment by shoumoji** [comment]
## 現状の完成状態

- [x] 活動記録
- [x] 運営規約
- [x] 会員名簿　

## 今後の流れ

既にほとんど提出書類ができているため、3/8までに一度ゆうちょで提出してみる。

審査は1か月ほどかかるそうなので、4月半ばぐらいまでには作っておきたい。

**Comment by shoumoji** [comment]
## 追加で必要なもの
- [ ] 総会議事録 (例会議事録で大丈夫そう)
- [ ] 収支報告書 (まだないので、予定として作る必要がある)
- [ ] HUITの印鑑 (注文済み)

## 今後
思ったより大変そう。とりあえずHUIT名義の印鑑は注文したが、3月に間に合うかは怪しい。

活動記録、運営規約、会員名簿は印刷したが、更に会員名簿に住所が必要そう。

**Comment by shoumoji** [comment]
改めて、現状考えていることを整理します。

## そもそも口座が必要な理由

- 部費, ハッカソンなどのお金が絡むことを既に行い始めているが、それを受け取る口座がない
- 金銭面で個人依存は最も避けたい
  - 引継ぎのリスクが今までと比べて段違いに大きい (金銭の受け渡しが発生する)
- とはいえ運営のモチベーションが高い時に、運営基盤が脆弱でできない、ということは今後避けたい 
- ドメイン・サーバなどの維持費や、例えばクラウドを使う時の費用を一括で纏めないと会計ができない

## 口座開設の現状について

正直かなり難しい。規約や事務所の所在地まで必要になっており、運営が個人レベルで行える範疇ではなくなり始めている。

対面であればお金を直接集めることで解決もできるが、現状だとそれも難しい。

そういったことを考えると、口座作成を始め任意団体としてできること自体に限度ある感じがした。

## 今考えていること

現状既に学生が個人レベルできることの範疇を超え始めているので、このまま任意団体のまま活動は現実的ではない。

金銭トラブルの元になることを考えると、まず北大の公認団体として登録し、運営基盤を作るべきだと考えている。

## 他の団体の話を聞いてみたい

正直複雑すぎて実際どうしてるんだろうこの辺と思っている。

他大学のサークルとかの運営について話を聞いてみたい。

公認サークルでもクレジットカードとか使えないとドメインの維持とか結局できないよね…。どうやってるんだろう。

**Comment by shoumoji** [comment]
工学部会も縮小傾向にあるらしく、少なくとも近いうちには難しそう。

色々会計上問題があるのは確かなので、公認化以外で道を探っても良いかもしれない。
