### ISSUE TITLE
技術的な質問をしやすいツールを作る

### ISSUE THREAD

**Issue by shoumoji** [HUITGroup/meeting#32]
## 概要

現状のtimesでは一部の人以外が技術的な質問をしにくい状態にある。

より質問を行いやすくするため、質問箱チャンネルを作り匿名での質問をしやすくする。

また、匿名での発言ができることから、意見を投げやすくできるのでは？という狙いもある。(特にOB絡みの件)

## TODO

- [ ] SPA(React) でDiscordのwebhookを叩けるようにする
- [ ]
- [ ]

## 留意事項

- 設置は一旦3月までに区切り、使用状況を見て存続させるかを決める
-

## 検討事項

- 既に作り始めている
-

**Comment by takapiro99** [comment]
前に slack 版でそれっぽいのを作ったことがあったので参考になれば！
https://github.com/takapiro99/slack-anonymous-tweet

**Comment by shoumoji** [comment]
質問箱作った

3月まで様子みてから今後考えます
