### ISSUE TITLE
GitHub Organization が三つあるので一つにしたい

### ISSUE THREAD

**Issue by takapiro99** [HUITGroup/meeting#34]
## 概要

- ここ
- https://github.com/HUITCLUB
- https://github.com/Hokkaido-University-IT

以上の３つに散らばっている（なんで？）

## 目的

分かりづらいから

## TODO

- [ ] 各 Organization の権限をもらう
- [x] レポジトリを一応全部 transfer する
- [ ] 不必要なOrganization を消す

## 留意事項

- なし

## 検討事項

- 旧 Organization でホスティングされてる https://huitclub.github.io/ をどうするか（とりあえず非公開にする、でよさそう）

**Comment by shoumoji** [comment]
賛成です、HUITGroupに統一しましょう

あと2つは誰が権限持ってるんだろう

**Comment by takapiro99** [comment]
https://github.com/Hokkaido-University-IT
これは @manattan が持ってるな

https://github.com/HUITCLUB
これはマジで分からん

**Comment by manattan** [comment]
自分が持っていた中のリポジトリをここに全部移しました。また、organization は削除しました

**Comment by shoumoji** [comment]
OBに連絡します

**Comment by takapiro99** [comment]
OBのほうに権限持ってる人いるかをたずねる

**Comment by shoumoji** [comment]
OB側に権限はあるっぽいけど、色々と込み入った事情があるっぽいので、そちらの統一は無理みたいです

現状できるところまで統一したので、クローズします。
