### ISSUE TITLE
SNS などの ID を統一したい

### ISSUE THREAD

**Issue by takapiro99** [HUITGroup/meeting#35]
## 概要

Twitter [@huitclub](https://twitter.com/huitclub)  
GitHub [@huitgroup](https://github.com/huitgroup)  
質問箱 [@huitclub](https://peing.net/ja/huitclub)

となっている

## 目的

分かりやすくしたい

## TODO

- [ ] どれにするかを決める
- [ ] そうでないやつを変更する

## 留意事項

-
-

## 検討事項

- どっちにするかを決める
-

**Comment by shoumoji** [comment]
利便性を考えると動いてるリポジトリのURLを変えたくない(Gitの再設定が面倒になる)ので、HUITGroupに統一したいところです

**Comment by takapiro99** [comment]
@shoumoji 変更できるところからやっちゃっていいですか？

**Comment by shoumoji** [comment]
そうですね、しましょうか

**Comment by takapiro99** [comment]
Twitter huitclub→huitgroup

**Comment by takapiro99** [comment]
質問箱も変えれた

ところで質問箱も使っていきませんか？

**Comment by shoumoji** [comment]
ありがとうございますー

質問箱に関して別issueたてました

https://github.com/HUITGroup/meeting/issues/40
