### ISSUE TITLE
メールとかDMとか取り逃がしすぎなのでDiscordに流してくれるBOTがほしい

### ISSUE THREAD

**Issue by takapiro99** [HUITGroup/meeting#36]
## 概要

メールとかDMとか取り逃がしすぎなのでDiscordに流してくれるBOTがほしい  

DMはメール通知にして、それをGASか何かでDiscordのwebhookを叩いて通知してくれるものがあれば便利

## 目的

メールとかDMとか取り逃がしすぎなので

## TODO

- [ ] やりたい人を募集する
- [ ] 作る（作ってもらう）
- [ ]

## 留意事項

- 作ったとしても運営権限の人しか見れないようにしたほうがいいかもしれない
-

## 検討事項

- これあったほうがいいですよね？
-

**Comment by takapiro99** [comment]
質問箱の通知は全体に流していいよな

**Comment by shoumoji** [comment]
便利そう

DMを流すのはやりたかったけど、技術力不足でTwitterのDMをどう取れば良いのか分からなくてやめました…

出来る人いればお願いしたいです

**Comment by takapiro99** [comment]
DM→メール通知→GASで転送 でできると思います

Twitter の他の通知もメール通知できるけど、いいねまで通知されてしまうからそれはGASではじく、とかもできるかもしれない

**Comment by takapiro99** [comment]
Discord から

- 担当決めておけばbotなどいらないのでは？
  - 作るのがめんどくさい
  - 技術負債になる

**Comment by takapiro99** [comment]
現時点でのちょっとした問題点

担当を決めていたとしても、複数人がログインしてる状態で誰か一人がDMを見ると他の人に通知がこない

でもメールなら気づけるかもね

**Comment by shoumoji** [comment]
たかぴろさんにお願いします！

**Comment by takapiro99** [comment]
作成しました
HUITのグーグルアカウントでGASを動かしています

![image](https://user-images.githubusercontent.com/55702777/112928932-7323bd80-9152-11eb-9c39-210f78b9df4d.png)

ソースはこちら  
https://github.com/HUITGroup/email-to-discord-notificator （非公開レポ）

**Comment by shoumoji** [comment]
ありがとうございます！

一応Googleフォーム→Discordに流すやつもGASで作ったので、ソース上げておきます。
https://gist.github.com/shoumoji/cb7f69beeb35dbc42d3c648e432e4d04
