### ISSUE TITLE
運営がclosed になっている

### ISSUE THREAD

**Issue by manattan** [HUITGroup/meeting#38]
## 概要
- 運営チャットが鍵テキストチャンネルなので、それ以外の人が何をしているか把握しづらい。内輪の盛り上がり団体になる危険性が高い。

## 検討事項
- general とかで積極的に公開していく、一人一人に積極的に声を掛ける、などの方法があるものの、人数が多くなったときにまとめづらい。よりお互いの距離が遠くなる気がする（感覚）

## 提案する手法
- 鍵をかけずに全て公開する。お金のことは共有したくないなどの声もあるだろうが、部費をとったり、誰かわからない人がdiscordに入っている状況は今後なくなるので、別にいいのでは。
- むしろお金のこと、そのプロセスも含めみんなが把握することで、運営が周りやすい、成長しやすいなどポジティブな面があるのではなかろうか。

**Comment by shoumoji** [comment]
５月ごろにやる
