### ISSUE TITLE
IT研ホームページ (の歴史)

### ISSUE THREAD

**Issue by takapiro99** [HUITGroup/meeting#7]
### what

実は過去に一度、サイトと [ブログ](https://huitclub.github.io/) が作(りかけ)られていた
2018の春～夏の開発。huitclub.comのドメインを取得していた模様？

そしてこちらがはてなブログ (https://huitclub.hatenablog.com/) 、2019/4 ~ 2019/6 しか運用されていなかったみたいだ
2018の活動内容が豪華だった

<br>

webサイト知らなかったので、新しく作るなら構成をきちんと考えたい

----

<br><br>

**旧ブログ** → SSG サイトで markdown で入稿するかたち、とても良いと思います
Ruby 製 SSG (静的サイトジェネレーター) の jekyll で github pages にデプロイしてるっぽい

(https://github.com/HUITCLUB/HUITCLUB.github.io#%E8%A8%98%E4%BA%8B%E3%81%AE%E6%9B%B8%E3%81%8D%E6%96%B9)

![image](https://user-images.githubusercontent.com/55702777/99677430-0bcb7200-2abd-11eb-842c-88deaa2e0767.png)

----

**サイト**

https://github.com/HUITCLUB/portfolio-site
(デプロイはされてなさそう)
express.js, mongoDBで作ってあって、ブログ管理とかもできる本格的な仕様っぽい

![image](https://user-images.githubusercontent.com/55702777/99677221-d2930200-2abc-11eb-9162-ca7cd7ffac8d.png)

----

サイト内メンバー紹介

![image](https://user-images.githubusercontent.com/55702777/99677346-f6564800-2abc-11eb-80df-1e7ca7794e4e.png)

----

サイト内ブログ(bootstrap)

![image](https://user-images.githubusercontent.com/55702777/99680205-23582a00-2ac0-11eb-9e24-a7e06cf310e0.png)

**Comment by takapiro99** [comment]
IT系のコミュニティとして、知ってもらう機会を作りたい

例えば参考
東工大 https://trap.jp/
京大 https://camph.net/
立命館 http://www.rcc.ritsumei.ac.jp/

**Comment by shoumoji** [comment]
[公式WEBサイトを作りたい](https://github.com/HUITGroup/meeting/issues/29) に統合
